import java.util.Scanner;
public class stringReverse
{
public static void main(String[] args)
{
System.out.println("PROGRAM TO REVERSE A STRING USING RECURSION");
System.out.println("ENTER THE STRING TO BE REVERSED USING RECURSION");
Scanner input = new Scanner(System.in);
String str = input.nextLine();
String reversed="";
System.out.println("THE REVERSED STRING IS: " +reverseString(str,"",0,str.length()-1) );
}
public static String reverseString()
 {

//TYPE YOUR CODE HERE

 }
}